export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
export const UPDATE_SORTED_COUNTRIES = "UPDATE_SORTED_COUNTRIES";
export const UPDATE_CURRENT_ORDER_TYPE = "UPDATE_CURRENT_ORDER_TYPE";


