export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
export const UPDATE_SORTED_COUNTRIES = "UPDATE_SORTED_COUNTRIES";
export const UPDATE_CURRENT_ORDER_TYPE = "UPDATE_CURRENT_ORDER_TYPE";
export const CREATE_TOURISM_COUNTRY = "CREATE_TOURISM_COUNTRY";
export const MODAL_TOURISM = "MODAL_TOURISM";
export const SET_TOURISM_ERROR = "SET_TOURISM_ERROR";
export const RESET_TOURISM_ERROR = "RESET_TOURISM_ERROR";




